### ISSUE TITLE
Warning for `activeTab` permission

### ISSUE THREAD

**Issue by bampakoa** [bampakoa/ngx-electronify#15]
The warning message `Permission 'activeTab' is unknown or URL pattern is malformed` is displayed when running the application.

**Comment by yhornik** [comment]
I would like to know if ngx-electronify use webPreferences.preload, if yes what is the path value ? what about contextIsolation, nodeIntegration values must we set ? true or false  ?

**Comment by bampakoa** [comment]
Hey @yhornik 👋 Ngx-electronify uses `contextIsolation` and `nodeIntegration` only when you set the `allowIntegration` option to `true`.

**Comment by yhornik** [comment]
I would like to know if I set contextIsolation=true and nodeIntegration=false, how and where can I use preload

**Comment by bampakoa** [comment]
Ngx-electronify does not make use of preload scripts for communicating with the renderer process. You can find more information at https://www.electronjs.org/docs/latest/tutorial/process-model#preload-scripts. I hope that helps 🙂
