### ISSUE TITLE
Add Angular CLI update schematic

### ISSUE THREAD

**Issue by bampakoa** [bampakoa/ngx-electronify#4]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to be able to update to the latest version using the `ng update` command

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Jefiozie** [comment]
What would you like to see in the first version of the update schematic?

**Comment by bampakoa** [comment]
I think that the update should make the following modifications:

1. Remove the library from the `dependencies` section of the `package.json`, which it is currently
2. Install the new version of the library

**Comment by Jefiozie** [comment]
This sounds like a great idea. Let's make it happen 💪

**Comment by bampakoa** [comment]
@Jefiozie I think that the 1st point is not needed since new users of the library will install the correct version with `devDependencies` and existing ones cannot use `ng update`. Is my assumption correct?

**Comment by bampakoa** [comment]
There is currently no need for any migration action with `ng update`.
